services:
  # Servicio de Base de Datos
  db:
    image: postgres:15
    container_name: turismo_db_container
    environment:
      - POSTGRES_DB=turismo_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123
    ports:
      - "5433:5432" # Para conectar desde IntelliJ

    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Aplicaci√≥n Spring Boot
  app:
    build: .
    container_name: turistik_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/turismo_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

volumes:
    postgres_data: